"""TraceCausal research contract helpers."""

from .adversarial_oracle import (
    AXIS_X_XI_GRID,
    ConfoundedFixture,
    StructuralReadout,
    axis_x_confounded,
    negative_control_collinear,
    source_swap,
    structural_equations,
)
from .binning_selection import Binning, SelectionEvent, select_binning
from .ciu import (
    CIURecord,
    CIUVerdict,
    baseline_readiness,
    calibrate_m_r,
    ciu_gate,
    g9_novelty_gate,
    g9_repair_gate,
    leakage_slope_regression,
    ood_deflation,
    ood_slope_ci_excludes_manufacture,
    validate_ciu_record,
)
from .contracts import EvidenceTier, ProjectContract, validate_manifest
from .interventions import (
    InterventionResult,
    MaskResult,
    PatchResult,
    ReplayResult,
    Span,
    mask,
    patch,
    replay,
)
from .metrics import intervention_effect, passes_intervention_gate
from .nuisance import (
    KappaEstimate,
    KappaFallback,
    SigmaEstimate,
    SigmaREstimate,
    apply_kappa_fallback,
    claim_level_aggregate,
    estimate_kappa,
    estimate_sigma_r,
    estimate_sigma_u,
    pool_inflation,
    r_power,
    r_power_repair,
    u_target,
)
from .nullpool import (
    CandidateSpan,
    NullPool,
    build_null_pool,
    pool_hash,
    proximity_bin,
    sample_matched_null,
    serialize_pool,
)
from .oracle_gen import (
    GradedOracleFixture,
    OracleExample,
    OracleSpan,
    clean_oracle,
    graded_oracle_family,
)
from .repair_ops import (
    EditedTargetPlan,
    OperatorGrid,
    OperatorSelection,
    PositivityFail,
    RepairPolicy,
    TargetClaimSpan,
    TargetEdit,
    apply,
    localized_repair,
    operator_grid_cardinality,
    policy_hash,
    select_operator,
    tracedet_ar_span_adapter,
    transport,
    transport_map_hash,
)
from .repair_transfer import (
    G9NovMargin,
    HajekVariance,
    PermutationResult,
    RepairGain,
    RHatEstimate,
    class_block_permutation,
    common_support_pairs,
    g9_nov_margin_simultaneous,
    hajek_projection_var,
    r_hat,
    repair_gain,
    target_clustered_mc_var,
    two_way_cluster_bootstrap,
)
from .schemas import TraceManifest, TraceSegment, TraceStep, validate_trace_manifest
from .selective_inference import (
    SiFloors,
    choose_si_path,
    holm_alpha,
    validate_selection_split,
)

__all__ = [
    # contracts
    "EvidenceTier",
    "ProjectContract",
    "validate_manifest",
    # schemas
    "TraceManifest",
    "TraceSegment",
    "TraceStep",
    "validate_trace_manifest",
    # metrics (unchanged public API)
    "intervention_effect",
    "passes_intervention_gate",
    # CIU Phase-2 contract (additive)
    "CIURecord",
    "CIUVerdict",
    "validate_ciu_record",
    "ciu_gate",
    "g9_repair_gate",
    "g9_novelty_gate",
    "calibrate_m_r",
    "baseline_readiness",
    "leakage_slope_regression",
    "ood_deflation",
    "ood_slope_ci_excludes_manufacture",
    # interventions (additive)
    "Span",
    "InterventionResult",
    "MaskResult",
    "PatchResult",
    "ReplayResult",
    "mask",
    "patch",
    "replay",
    # null pool (additive)
    "CandidateSpan",
    "NullPool",
    "build_null_pool",
    "sample_matched_null",
    "serialize_pool",
    "pool_hash",
    "proximity_bin",
    # nuisance estimators (additive)
    "SigmaEstimate",
    "SigmaREstimate",
    "KappaEstimate",
    "KappaFallback",
    "estimate_sigma_u",
    "estimate_sigma_r",
    "estimate_kappa",
    "claim_level_aggregate",
    "apply_kappa_fallback",
    "pool_inflation",
    "r_power",
    "r_power_repair",
    "u_target",
    # graded oracle (additive)
    "OracleSpan",
    "OracleExample",
    "GradedOracleFixture",
    "clean_oracle",
    "graded_oracle_family",
    # --- v5 additive surfaces (REDESIGN_v5) ---
    # repair_ops (Variant C transport)
    "RepairPolicy",
    "TargetClaimSpan",
    "TargetEdit",
    "PositivityFail",
    "EditedTargetPlan",
    "OperatorGrid",
    "OperatorSelection",
    "localized_repair",
    "transport",
    "apply",
    "operator_grid_cardinality",
    "select_operator",
    "policy_hash",
    "transport_map_hash",
    "tracedet_ar_span_adapter",
    # repair_transfer (R_hat U-statistic + inference)
    "RepairGain",
    "RHatEstimate",
    "PermutationResult",
    "HajekVariance",
    "G9NovMargin",
    "repair_gain",
    "r_hat",
    "two_way_cluster_bootstrap",
    "class_block_permutation",
    "hajek_projection_var",
    "target_clustered_mc_var",
    "common_support_pairs",
    "g9_nov_margin_simultaneous",
    # binning_selection (selection-as-code)
    "Binning",
    "SelectionEvent",
    "select_binning",
    # selective_inference (Holm fold + SI path)
    "SiFloors",
    "holm_alpha",
    "validate_selection_split",
    "choose_si_path",
    # adversarial_oracle (Axis X')
    "AXIS_X_XI_GRID",
    "ConfoundedFixture",
    "StructuralReadout",
    "structural_equations",
    "axis_x_confounded",
    "negative_control_collinear",
    "source_swap",
]
